# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

language: node_js
node_js:
  - '0.10'
env:
  global:
    - TIMEOUT=1000
    - secure: rKxGaPkWoXDJg0NRWueqnmecEzoKopfuUSAnkh5oe93wjEeSUYsz/a0+ocly8Ba109ZdmxAGXbEh26BPAGcjoiOPqfGa5ihditYnqxKkCJtQBbkI4Ld811Ez6sJNwLaHtCLF2UPXaBKQR67wHs9AFPFm5SzVlO+Rdqgrc6EoKA==
    - secure: bW3DVc9NZfLtQTq+5jQw7BQDXYYHT6hQ5XMvrFdKz6676ELakyNzqGDoDnYaRvZpkR+8+eFIyE8bS/wNaWx4o9BGCycREQfS5cLsle3m36aOV4SUtwxhYq3eW34jbk32Qvw6a16XC+EB9gWlgaIX5zJ+krVu387BGpNC7BJeHz4=
