ui: tape
browsers:
  - name: android
    version: 4.0
  - name: android
    version: 4.1
  - name: android
    version: 4.2
  - name: android
    version: 4.3
  - name: android
    version: 4.4
  - name: android
    version: 5.0
  - name: android
    version: 5.1
